name: nla_py311
channels:
  - anaconda
  - fastai
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alsa-lib=1.2.13
  - attr=2.5.1
  - binutils_impl_linux-64=2.43
  - blas=1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2025.1.31
  - cairo=1.18.2
  - certifi=2025.1.31
  - cffi=1.17.1
  - charset-normalizer=3.3.2
  - click=8.1.7
  - cloudpickle=3.0.0
  - contourpy=1.3.1
  - cryptography=43.0.3
  - cycler=0.11.0
  - cyrus-sasl=2.1.27
  - dbus=1.13.18
  - expat=2.6.4
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=2.001
  - font-ttf-source-code-pro=2.030
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-anaconda=1
  - fonts-conda-ecosystem=1
  - fonttools=4.55.3
  - freetype=2.12.1
  - future=1.0.0
  - gcc=12.1.0
  - gcc_impl_linux-64=12.1.0
  - gensim=4.3.3
  - gettext=0.23.1
  - gettext-tools=0.23.1
  - glib=2.82.2
  - glib-tools=2.82.2
  - graphite2=1.3.14
  - gst-plugins-base=1.24.7
  - gstreamer=1.24.7
  - harfbuzz=10.3.0
  - hyperopt=0.2.7
  - icu=75.1
  - idna=3.7
  - iniconfig=1.1.1
  - isodate=0.7.2
  - joblib=1.4.2
  - kernel-headers_linux-64=3.10.0
  - kiwisolver=1.4.8
  - krb5=1.21.3
  - lame=3.100
  - lcms2=2.17
  - ld_impl_linux-64=2.43
  - lerc=4.0.0
  - libasprintf=0.23.1
  - libasprintf-devel=0.23.1
  - libcap=2.71
  - libclang-cpp19.1=19.1.7
  - libclang13=19.1.7
  - libcups=2.3.3
  - libdeflate=1.23
  - libdrm=2.4.124
  - libedit=3.1.20230828
  - libegl=1.7.0
  - libevent=2.1.12
  - libexpat=2.6.4
  - libffi=3.4.6
  - libflac=1.4.3
  - libgcc=14.2.0
  - libgcc-devel_linux-64=12.1.0
  - libgcc-ng=14.2.0
  - libgcrypt-lib=1.11.0
  - libgettextpo=0.23.1
  - libgettextpo-devel=0.23.1
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgl=1.7.0
  - libglib=2.82.2
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=14.2.0
  - libgpg-error=1.51
  - libiconv=1.18
  - libjpeg-turbo=3.0.3
  - libllvm19=19.1.7
  - liblzma=5.6.4
  - liblzma-devel=5.6.4
  - libnsl=2.0.1
  - libntlm=1.6
  - libogg=1.3.5
  - libopenblas=0.3.21
  - libopus=1.3.1
  - libpciaccess=0.18
  - libpng=1.6.47
  - libpq=17.4
  - libsanitizer=12.1.0
  - libsndfile=1.2.2
  - libsqlite=3.49.1
  - libstdcxx=14.2.0
  - libstdcxx-ng=12.3.0
  - libsystemd0=257.3
  - libtiff=4.7.0
  - libuuid=2.38.1
  - libvorbis=1.3.7
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libxkbcommon=1.8.0
  - libxml2=2.13.6
  - libxslt=1.1.41
  - libzlib=1.3.1
  - lxml=5.3.0
  - lz4-c=1.10.0
  - matplotlib=3.10.0
  - matplotlib-base=3.10.0
  - mpg123=1.32.9
  - mysql-common=9.0.1
  - mysql-libs=9.0.1
  - ncurses=6.5
  - networkx=3.4.2
  - nltk=3.9.1
  - nspr=4.36
  - nss=3.108
  - numpy=1.26.4
  - numpy-base=1.26.4
  - nvidia-ml-py3=7.352.0
  - openjpeg=2.5.3
  - openldap=2.6.9
  - openssl=3.4.1
  - packaging=24.2
  - pcre2=10.44
  - pillow=11.1.0
  - pip=25.0.1
  - pixman=0.44.2
  - pluggy=1.5.0
  - ply=3.11
  - psutil=5.9.0
  - pthread-stubs=0.3
  - pulseaudio-client=17.0
  - py4j=0.10.9.7
  - pybind11-abi=4
  - pycparser=2.21
  - pyopenssl=24.2.1
  - pyparsing=3.2.0
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - pysocks=1.7.1
  - pytest=8.3.4
  - python=3.11.6
  - python-dateutil=2.9.0post0
  - python_abi=3.11
  - pyyaml=6.0.2
  - qt-main=5.15.15
  - rdflib=7.1.3
  - readline=8.2
  - regex=2024.11.6
  - requests=2.32.3
  - scikit-learn=1.6.1
  - scipy=1.13.1
  - setuptools=75.8.0
  - sip=6.7.12
  - six=1.16.0
  - smart_open=5.2.1
  - sparqlwrapper=2.0.0
  - sysroot_linux-64=2.17
  - threadpoolctl=3.5.0
  - tk=8.6.13
  - tornado=6.4.2
  - tqdm=4.67.1
  - tzdata=2025a
  - unicodedata2=15.1.0
  - urllib3=2.3.0
  - wheel=0.45.1
  - xcb-util=0.4.1
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xkeyboard-config=2.43
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.5
  - xorg-libx11=1.8.11
  - xorg-libxau=1.0.12
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxrender=0.9.12
  - xorg-libxxf86vm=1.1.6
  - xz=5.6.4
  - xz-gpl-tools=5.6.4
  - xz-tools=5.6.4
  - yaml=0.2.5
  - zstd=1.5.7
  - pip:
      - accelerate==1.4.0
      - attrs==25.1.0
      - beautifulsoup4==4.13.3
      - bioc==2.1
      - boto3==1.36.26
      - botocore==1.36.26
      - conllu==4.5.3
      - deprecated==1.2.18
      - docopt==0.6.2
      - filelock==3.17.0
      - flair==0.15.1
      - fsspec==2025.2.0
      - ftfy==6.3.1
      - gdown==5.2.0
      - germalemma==0.1.3
      - huggingface-hub==0.29.1
      - intervaltree==3.1.0
      - jinja2==3.1.5
      - jmespath==1.0.1
      - jsonlines==4.0.0
      - langdetect==1.0.9
      - markupsafe==3.0.2
      - more-itertools==10.6.0
      - mpld3==0.5.10
      - mpmath==1.3.0
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - patternlite==3.6
      - pptree==3.1
      - protobuf==5.29.3
      - pyphen==0.17.2
      - pytorch-revgrad==0.2.0
      - s3transfer==0.11.2
      - safetensors==0.5.2
      - segtok==1.5.11
      - sentencepiece==0.2.0
      - sortedcontainers==2.4.0
      - soupsieve==2.6
      - sqlitedict==2.1.0
      - sympy==1.13.1
      - tabulate==0.9.0
      - tokenizers==0.21.0
      - torch==2.6.0
      - transformer-smaller-training-vocab==0.4.0
      - transformers==4.49.0
      - triton==3.2.0
      - typing-extensions==4.12.2
      - wcwidth==0.2.13
      - wikipedia-api==0.8.1
      - wrapt==1.17.2